CONFIG_ENV=config.properties
KERNEL_SOURCE=SK-Aeveyn233/TALIH-PD2-Kernel
KERNEL_SOURCE_BRANCH=main
KERNEL_CONFIG=ls12_mt8797_wifi_64_defconfig
KERNEL_IMAGE_NAME=Image.gz
ARCH=arm64
ENABLE_GCC_ARM64=true
ENABLE_GCC_ARM32=true
ENABLE_KERNELSU=true
KERNELSU_SOURCE=https://github.com/SukiSU-Ultra/SukiSU-Ultra
KERNELSU_BRANCH=main
DISABLE_LTO=true
DISABLE_CC_WERROR=true
ADD_KPROBES_CONFIG=false
ENABLE_CCACHE=true
REMOVE_UNUSED_PACKAGES=true
